backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "src/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 1}
      - {label: "Category", name: "category", widget: "select", options: ["Basics", "JL Docs"]}
      - {label: "Body", name: "body", widget: "markdown"}